name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "TACACS+ in Erlang tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [21, 22, 23, 24, 25, 26]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Common Tests
      run: rebar3 ct
