name: tacacs_client

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['25.2']
        rebar3: ['3.22.1']
    steps:
    - name: Set up Erlang ${{ matrix.python-version }}
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar3}}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tacacs_plus
    - name: Setup etacacs_plus
      uses: actions/checkout@v3
      - run: rebar3 ct
